#!/usr/bin/env bash
# Script: Affiche les ports TCP/UDP et les sockets UNIX en écoute avec PID et programme

# Affiche les connexions Internet (TCP et UDP) en écoute
echo "Active Internet connections (only servers)"
ss -tulnp

# Affiche les sockets UNIX en écoute
echo "Active UNIX domain sockets (only servers)"
ss -xlnp
