#!/bin/bash
# Script: 5-is_the_host_on_the_network
# Objectif: Pinguer une adresse IP passée en argument

# Vérifier si un argument est fourni
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Pinguer l'adresse IP 5 fois
ping -c 5 "$1"
